spring:
  application:
    name: feature-flag-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/feature_flag_db



server:
  port: 8081

tracking-order:
  service:
    url: http://localhost:8080
  sync-token: change-me


logging:
  level:
    com.example.featureflagservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

togglz:
  enabled: true
  console:
    enabled: true
    path: /togglz-console
    secured: true
  feature-enums: com.example.featureflagservice.common.FeatureFlags
